function Seq = init_seq

% Initialise sequences for testing
%
% Jingjing Xiao, 2016
%

Seq={... 
    struct('name','butterfly','path','../DSTdataset/butterfly/','startFrame',1,'endFrame',151,'nz',8,'ext','jpg','gt', 'GT.txt'),...  
    struct('name','leaves','path','../DSTdataset/leaves/','startFrame',1,'endFrame',63,'nz',8,'ext','jpg','gt', 'GT.txt'),...  
    struct('name','bolt1','path','../DSTdataset/bolt1/','startFrame',1,'endFrame',350,'nz',8,'ext','jpg','gt', 'GT.txt'),...   
    struct('name','glove','path','../DSTdataset/glove/','startFrame',1,'endFrame',120,'nz',8,'ext','jpg','gt', 'GT.txt'),...     
    struct('name','sheep','path','../DSTdataset/sheep/','startFrame',1,'endFrame',251,'nz',8,'ext','jpg','gt', 'GT.txt'),...    
    struct('name','crowd_1','path','../DSTdataset/crowd/','startFrame',1,'endFrame',250,'nz',8,'ext','jpg','gt', 'GTcrowd_1.txt'),...
    struct('name','marching','path','../DSTdataset/marching/','startFrame',1,'endFrame',201,'nz',8,'ext','jpg','gt', 'GT.txt'),...
    struct('name','bolt2','path','../DSTdataset/bolt2/','startFrame',1,'endFrame',293,'nz',8,'ext','jpg','gt', 'GT.txt'),...    
    struct('name','basketball','path','../DSTdataset/basketball/','startFrame',1,'endFrame',725,'nz',8,'ext','jpg','gt', 'GT.txt'),... 
    struct('name','birds2','path','../DSTdataset/birds2/','startFrame',1,'endFrame',539,'nz',8,'ext','jpg','gt', 'GT.txt'),...
    struct('name','fish1','path','../DSTdataset/fish1/','startFrame',1,'endFrame',366,'nz',8,'ext','jpg','gt', 'GT.txt'),...
    struct('name','fish2','path','../DSTdataset/fish2/','startFrame',1,'endFrame',310,'nz',8,'ext','jpg','gt', 'GT.txt'),...    
    struct('name','fish3','path','../DSTdataset/fish3/','startFrame',1,'endFrame',519,'nz',8,'ext','jpg','gt', 'GT.txt'),...  
    struct('name','fish4','path','../DSTdataset/fish4/','startFrame',1,'endFrame',682,'nz',8,'ext','jpg','gt', 'GT.txt'),...
    struct('name','rabbit','path','../DSTdataset/rabbit/','startFrame',1,'endFrame',158,'nz',8,'ext','jpg','gt', 'GT.txt'),...   
    struct('name','soccer1','path','../DSTdataset/soccer1/','startFrame',1,'endFrame',392,'nz',8,'ext','jpg','gt', 'GT.txt'),...     
    struct('name','running_1','path','../DSTdataset/running/','startFrame',1,'endFrame',155,'nz',8,'ext','jpg','gt', 'GTrunning_1.txt'),...   
    struct('name','running_2','path','../DSTdataset/running/','startFrame',1,'endFrame',155,'nz',8,'ext','jpg','gt', 'GTrunning_2.txt'),...   
    struct('name','running_3','path','../DSTdataset/running/','startFrame',1,'endFrame',155,'nz',8,'ext','jpg','gt', 'GTrunning_3.txt'),...  
    struct('name','tud_campus_1','path','../DSTdataset/tud_campus/','startFrame',1,'endFrame',71,'nz',8,'ext','png','gt', 'GTtud_campus_1.txt'),... 
    struct('name','juggling_1','path','../DSTdataset/juggling/','startFrame',1,'endFrame',130,'nz',8,'ext','jpg','gt', 'GTjuggling_1.txt'),...
    struct('name','juggling_2','path','../DSTdataset/juggling/','startFrame',1,'endFrame',130,'nz',8,'ext','jpg','gt', 'GTjuggling_2.txt'),...
    struct('name','juggling_3','path','../DSTdataset/juggling/','startFrame',1,'endFrame',130,'nz',8,'ext','jpg','gt', 'GTjuggling_3.txt'),...
    struct('name','crowd_2','path','../DSTdataset/crowd/','startFrame',1,'endFrame',250,'nz',8,'ext','jpg','gt', 'GTcrowd_2.txt'),...
    struct('name','crowd_3','path','../DSTdataset/crowd/','startFrame',1,'endFrame',250,'nz',8,'ext','jpg','gt', 'GTcrowd_3.txt'),...
    struct('name','crowd_4','path','../DSTdataset/crowd/','startFrame',1,'endFrame',250,'nz',8,'ext','jpg','gt', 'GTcrowd_4.txt'),...
    struct('name','crowd_5','path','../DSTdataset/crowd/','startFrame',1,'endFrame',250,'nz',8,'ext','jpg','gt', 'GTcrowd_5.txt'),...
    struct('name','crowd_6','path','../DSTdataset/crowd/','startFrame',1,'endFrame',250,'nz',8,'ext','jpg','gt', 'GTcrowd_6.txt'),...
};